/* Alya'nın Oyunları — Service Worker */

/* Uygulama dosyaları: her sürümde yenilenir */
const CORE_CACHE = 'alya-core-v10.1.0';
/* Ses ve görseller: sürümden bağımsız, bir kez inip kalır */
const MEDIA_CACHE = 'alya-media-v1';

const CORE = [
  './',
  './index.html',
  './app.css',
  './manifest.webmanifest',
  './util.js',
  './audio.js',
  './mascot.js',
  './fx.js',
  './game-numbers.js',
  './game-shapes.js',
  './game-letters.js',
  './game-memory.js',
  './game-dua.js',
  './game-abdest.js',
'./game-sofra.js',
'./game-dis.js',
  './motor.js',
  './game-hikaye.js',
  './game-kelime.js',
  './game-arapharf.js',
  './game-giydirme.js',
  './game-yaratici.js',
  './game-hareket.js',
  './veri-ahlak.js',
  './veri-temizlik.js',
  './veri-dini.js',
  './veri-moda.js',
  './veri-hikaye.js',
  './surukle.js',
  './motor-rutin.js',
  './veri-rutin.js',
  './game-toplan.js',
  './game-agac.js',
  './game-duygu.js',
  './app.js',
  './icon-192.png',
  './icon-512.png',
  './icon-maskable-512.png'
];

const SES = [
  'abdest-1',
  'abdest-2',
  'abdest-3',
  'abdest-4',
  'abdest-5',
  'abdest-6',
  'ad-araba',
  'ad-balik',
  'ad-balon',
  'ad-cicek',
  'ad-cilek',
  'ad-civciv',
  'ad-davul',
  'ad-elma',
  'ad-fil',
  'ad-gul',
  'ad-horoz',
  'ad-kedi',
  'ad-kelebek',
  'ad-kurabiye',
  'ad-muz',
  'ad-ordek',
  'ad-robot',
  'ad-sapka',
  'ad-top',
  'ad-ugurbocegi',
  'ad-uzum',
  'ad-yildiz',
  'anlam-bismillah',
  'anlam-elhamdulillah',
  'anlam-insallah',
  'anlam-masallah',
  'anlam-razi',
  'anlam-selam',
  'dis-bitti',
  'dis-devam',
  'dis-firca',
  'dua-arkadas',
  'dua-bebek',
  'dua-cami',
  'dua-eve-girer',
  'dua-guzel',
  'dua-ikram',
  'dua-ise-basla',
  'dua-iyilesme',
  'dua-resim',
  'dua-uyku',
  'dua-yagmur',
  'dua-yardim',
  'dua-yarin',
  'dua-yemek-basi',
  'dua-yemek-sonu',
  'dua-yol',
  'harf-a',
  'harf-b',
  'harf-c',
  'harf-cc',
  'harf-d',
  'harf-e',
  'harf-f',
  'harf-g',
  'harf-h',
  'harf-i',
  'harf-ii',
  'harf-j',
  'harf-k',
  'harf-l',
  'harf-m',
  'harf-n',
  'harf-o',
  'harf-oo',
  'harf-p',
  'harf-r',
  'harf-s',
  'harf-ss',
  'harf-t',
  'harf-u',
  'harf-uu',
  'harf-v',
  'harf-y',
  'harf-z',
  'kelime-aslan',
  'kelime-balik',
  'kelime-cilek',
  'kelime-civciv',
  'kelime-davul',
  'kelime-elma',
  'kelime-fil',
  'kelime-gul',
  'kelime-horoz',
  'kelime-inek',
  'kelime-isik',
  'kelime-jaguar',
  'kelime-kedi',
  'kelime-limon',
  'kelime-muz',
  'kelime-nota',
  'kelime-ordek',
  'kelime-otobus',
  'kelime-pasta',
  'kelime-robot',
  'kelime-sapka',
  'kelime-sut',
  'kelime-top',
  'kelime-ucak',
  'kelime-uzum',
  'kelime-vazo',
  'kelime-yildiz',
  'kelime-zurafa',
  'nesne-araba',
  'nesne-balik',
  'nesne-balon',
  'nesne-cicek',
  'nesne-cilek',
  'nesne-civciv',
  'nesne-elma',
  'nesne-kelebek',
  'nesne-kurabiye',
  'nesne-muz',
  'nesne-ugurbocegi',
  'nesne-yildiz',
  'not-harf-a',
  'not-harf-b',
  'not-harf-c',
  'not-harf-cc',
  'not-harf-d',
  'not-harf-e',
  'not-harf-f',
  'not-harf-g',
  'not-harf-h',
  'not-harf-i',
  'not-harf-ii',
  'not-harf-j',
  'not-harf-k',
  'not-harf-l',
  'not-harf-m',
  'not-harf-n',
  'not-harf-o',
  'not-harf-oo',
  'not-harf-p',
  'not-harf-r',
  'not-harf-s',
  'not-harf-ss',
  'not-harf-t',
  'not-harf-u',
  'not-harf-uu',
  'not-harf-v',
  'not-harf-y',
  'not-harf-z',
  'not-renk-kirmizi',
  'not-renk-mavi',
  'not-renk-mor',
  'not-renk-pembe',
  'not-renk-sari',
  'not-renk-turuncu',
  'not-renk-yesil',
  'not-sekil-daire',
  'not-sekil-dikdortgen',
  'not-sekil-kalp',
  'not-sekil-kare',
  'not-sekil-ucgen',
  'not-sekil-yildiz',
  'ovgu-1',
  'ovgu-2',
  'ovgu-3',
  'ovgu-4',
  'ovgu-5',
  'ovgu-6',
  'ovgu-7',
  'renk-kirmizi',
  'renk-mavi',
  'renk-mor',
  'renk-pembe',
  'renk-sari',
  'renk-turuncu',
  'renk-yesil',
  'rs-kirmizi-daire',
  'rs-kirmizi-dikdortgen',
  'rs-kirmizi-kalp',
  'rs-kirmizi-kare',
  'rs-kirmizi-ucgen',
  'rs-kirmizi-yildiz',
  'rs-mavi-daire',
  'rs-mavi-dikdortgen',
  'rs-mavi-kalp',
  'rs-mavi-kare',
  'rs-mavi-ucgen',
  'rs-mavi-yildiz',
  'rs-mor-daire',
  'rs-mor-dikdortgen',
  'rs-mor-kalp',
  'rs-mor-kare',
  'rs-mor-ucgen',
  'rs-mor-yildiz',
  'rs-pembe-daire',
  'rs-pembe-dikdortgen',
  'rs-pembe-kalp',
  'rs-pembe-kare',
  'rs-pembe-ucgen',
  'rs-pembe-yildiz',
  'rs-sari-daire',
  'rs-sari-dikdortgen',
  'rs-sari-kalp',
  'rs-sari-kare',
  'rs-sari-ucgen',
  'rs-sari-yildiz',
  'rs-turuncu-daire',
  'rs-turuncu-dikdortgen',
  'rs-turuncu-kalp',
  'rs-turuncu-kare',
  'rs-turuncu-ucgen',
  'rs-turuncu-yildiz',
  'rs-yesil-daire',
  'rs-yesil-dikdortgen',
  'rs-yesil-kalp',
  'rs-yesil-kare',
  'rs-yesil-ucgen',
  'rs-yesil-yildiz',
  'sayi-1',
  'sayi-10',
  'sayi-2',
  'sayi-3',
  'sayi-4',
  'sayi-5',
  'sayi-6',
  'sayi-7',
  'sayi-8',
  'sayi-9',
  'sekil-daire',
  'sekil-dikdortgen',
  'sekil-kalp',
  'sekil-kare',
  'sekil-ucgen',
  'sekil-yildiz',
  'sofra-1',
  'sofra-1-neden',
  'sofra-10',
  'sofra-10-neden',
  'sofra-11',
  'sofra-11-neden',
  'sofra-12',
  'sofra-12-neden',
  'sofra-2',
  'sofra-2-neden',
  'sofra-3',
  'sofra-3-neden',
  'sofra-4',
  'sofra-4-neden',
  'sofra-5',
  'sofra-5-neden',
  'sofra-6',
  'sofra-6-neden',
  'sofra-7',
  'sofra-7-neden',
  'sofra-8',
  'sofra-8-neden',
  'sofra-9',
  'sofra-9-neden',
  'soru-1',
  'soru-10',
  'soru-2',
  'soru-3',
  'soru-4',
  'soru-5',
  'soru-6',
  'soru-7',
  'soru-8',
  'soru-9',
  'soz-bismillah',
  'soz-elhamdulillah',
  'soz-insallah',
  'soz-masallah',
  'soz-razi',
  'soz-selam',
  'sys-abdest-devam',
  'sys-hafiza-bak',
  'sys-hafiza-devam',
  'sys-hafiza-esles',
  'sys-harf-ayni',
  'sys-harf-ses',
  'sys-merhaba',
  'sys-oyun-abdest',
  'sys-oyun-dis',
  'sys-oyun-dua',
  'sys-oyun-hafiza',
  'sys-oyun-harf',
  'sys-oyun-renk',
  'sys-oyun-sayi',
  'sys-oyun-sofra',
  'sys-yakinda',
  'sys-yildiz-1',
  'sys-yildiz-2',
  'sys-yildiz-3',
  'tekrar-1',
  'tekrar-2',
  'tekrar-3',
  'tekrar-4',
].map(id => './sesler/' + id + '.mp3');

const GORSEL = [
  'elif',
  'kategori-ahlak',
  'kategori-dini',
  'kategori-hareket',
  'kategori-harf',
  'kategori-moda',
  'kategori-yaratici',
  'kategori-zeka',
  'lina',
  'mina-alkis',
  'mina-dua',
  'mina-dusunuyor',
  'mina-mutlu',
  'mina-normal',
  'mina-uzgun',
  'oyun-abdest',
  'oyun-agac',
  'oyun-arapharf',
  'oyun-bahce',
  'oyun-bayram',
  'oyun-boyama',
  'oyun-bugun',
  'oyun-cami',
  'oyun-cizim',
  'oyun-dua',
  'oyun-duygu',
  'oyun-empati',
  'oyun-gorev',
  'oyun-guzelsoz',
  'oyun-hareket',
  'oyun-hikaye',
  'oyun-ilahi',
  'oyun-kabe',
  'oyun-kelime',
  'oyun-kombin',
  'oyun-letters',
  'oyun-memory',
  'oyun-moda',
  'oyun-muzik',
  'oyun-nefes',
  'oyun-numbers',
  'oyun-paylasma',
  'oyun-peygamber',
  'oyun-ramazan',
  'oyun-renkuyum',
  'oyun-shapes',
  'rozet-1',
  'rozet-2',
  'rozet-3',
  'rozet-4',
  'rozet-5',
  'sare',
  'zeynep',
  'pati-normal',
  'pati-mutlu',
  'pati-alkis',
  'pati-dusunuyor',
  'pati-uzgun',
  'pati-selam',
  'kategori-temizlik',
  'oyun-sofra',
  'oyun-dis',
  'oyun-elyikama',
  'oyun-banyo',
  'oyun-toplan',
  'oyun-rutin',
  'oyun-saglik',
  'oyun-giyinme',
].map(id => './gorseller/' + id + '.webp');

const MEDYA = SES.concat(GORSEL);

/* Kurulum: SADECE uygulama dosyaları. Medyayı burada indirmiyoruz —
   yoksa ilk açılışta 158 istek ağı tıkıyor ve uygulama geç açılıyor. */
self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CORE_CACHE)
      .then(c => c.addAll(CORE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys.filter(k => k !== CORE_CACHE && k !== MEDIA_CACHE).map(k => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

/* Medyayı sayfa tamamen açıldıktan sonra, azar azar indir */
let medyaCalisiyor = false;
async function medyaDoldur() {
  if (medyaCalisiyor) return;
  medyaCalisiyor = true;
  try {
    const c = await caches.open(MEDIA_CACHE);
    const eksik = [];
    for (const u of MEDYA) { if (!(await c.match(u))) eksik.push(u); }
    // 5'erli gruplar hâlinde, aralarda nefes payı bırakarak
    for (let i = 0; i < eksik.length; i += 5) {
      await Promise.allSettled(eksik.slice(i, i + 5).map(u => c.add(u).catch(() => {})));
      await new Promise(r => setTimeout(r, 120));
    }
  } catch (e) {} finally { medyaCalisiyor = false; }
}

self.addEventListener('message', e => {
  if (e.data && e.data.tip === 'medya-yukle') e.waitUntil(medyaDoldur());
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  // Gezinme: önce ağ, olmazsa cache
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req).then(r => {
        const copy = r.clone();
        caches.open(CORE_CACHE).then(c => c.put('./index.html', copy));
        return r;
      }).catch(() => caches.match('./index.html'))
    );
    return;
  }

  const medyaMi = url.pathname.includes('/sesler/') || url.pathname.includes('/gorseller/');

  e.respondWith((async () => {
    const hit = await caches.match(req);
    if (hit) return hit;
    try {
      const r = await fetch(req);
      if (r && r.status === 200) {
        const c = await caches.open(medyaMi ? MEDIA_CACHE : CORE_CACHE);
        c.put(req, r.clone());
      }
      return r;
    } catch (err) {
      return hit || Response.error();
    }
  })());
});
