/* ===== Ahlak ve Arkadaşlık — 5 oyun ===== */

/* 1) Duyguları Tanı */
window.GameDuygu = Motor.secmece({
  id: 'duygu', title: 'Duyguları<br>Tanı', emoji: '😊',
  intro: { id: 'sys-oyun-duygu', text: 'Yüzlere bakalım, hangi duygu olduğunu bulalım!' },
  havuz: {
    mutlu:  { e: '😄', t: 'Mutlu',    id: 'duy-mutlu' },
    uzgun:  { e: '😢', t: 'Üzgün',    id: 'duy-uzgun' },
    kizgin: { e: '😠', t: 'Kızgın',   id: 'duy-kizgin' },
    korkmus:{ e: '😨', t: 'Korkmuş',  id: 'duy-korkmus' },
    saskin: { e: '😲', t: 'Şaşkın',   id: 'duy-saskin' },
    yorgun: { e: '😴', t: 'Yorgun',   id: 'duy-yorgun' },
    utangac:{ e: '😊', t: 'Utangaç',  id: 'duy-utangac' }
  },
  durumlar: [
    { e: '😄', soru: 'Bu yüz ne hissediyor?', dogru: 'mutlu',   id: 'duygu-1',
      neden: 'Ağzı gülüyor, gözleri parlıyor. Mutlu olunca içimiz ısınır.' },
    { e: '😢', soru: 'Bu yüz ne hissediyor?', dogru: 'uzgun',   id: 'duygu-2',
      neden: 'Gözünden yaş geliyor. Üzülmek normaldir, geçer.' },
    { e: '😠', soru: 'Bu yüz ne hissediyor?', dogru: 'kizgin',  id: 'duygu-3',
      neden: 'Kaşları çatık. Kızınca derin nefes alırsak sakinleşiriz.' },
    { e: '😨', soru: 'Bu yüz ne hissediyor?', dogru: 'korkmus', id: 'duygu-4',
      neden: 'Gözleri kocaman açılmış. Korkunca birine söylemek rahatlatır.' },
    { e: '😲', soru: 'Bu yüz ne hissediyor?', dogru: 'saskin',  id: 'duygu-5',
      neden: 'Beklemediği bir şey olmuş. Şaşırmak eğlencelidir.' },
    { e: '😴', soru: 'Bu yüz ne hissediyor?', dogru: 'yorgun',  id: 'duygu-6',
      neden: 'Gözleri kapanıyor. Yorulunca dinlenmek gerekir.' },
    { e: '🎁', soru: 'Hediye alan çocuk ne hisseder?',      dogru: 'mutlu',   id: 'duygu-7',
      neden: 'Sevdiğimiz bir şey olunca mutlu oluruz.' },
    { e: '🧸', soru: 'Oyuncağı kırılan çocuk ne hisseder?', dogru: 'uzgun',   id: 'duygu-8',
      neden: 'Sevdiğimiz bir şeyi kaybedince üzülürüz.' },
    { e: '🌩️', soru: 'Gök gürleyince ne hissederiz?',       dogru: 'korkmus', id: 'duygu-9',
      neden: 'Yüksek ses korkutabilir ama gök gürültüsü zarar vermez.' },
    { e: '🛏️', soru: 'Bütün gün oynayan çocuk akşam ne hisseder?', dogru: 'yorgun', id: 'duygu-10',
      neden: 'Çok oynayınca vücudumuz dinlenmek ister.' },
    { e: '🎂', soru: 'Sürpriz parti gören çocuk ne hisseder?', dogru: 'saskin', id: 'duygu-11',
      neden: 'Hiç beklemediği bir şey olunca şaşırır.' },
    { e: '🙈', soru: 'Yeni insanlarla tanışınca ne hissedebiliriz?', dogru: 'utangac', id: 'duygu-12',
      neden: 'Utanmak normaldir. Biraz zaman geçince alışırız.' }
  ]
});

/* 2) Empati Oyunu */
window.GameEmpati = Motor.secmece({
  id: 'empati', title: 'Empati<br>Oyunu', emoji: '🤝',
  intro: { id: 'sys-oyun-empati', text: 'Karşımızdaki ne hisseder, birlikte düşünelim!' },
  havuz: {
    sevinir:  { e: '🥰', t: 'Sevinir',      id: 'emp-sevinir' },
    uzulur:   { e: '😔', t: 'Üzülür',       id: 'emp-uzulur' },
    korkar:   { e: '😰', t: 'Korkar',       id: 'emp-korkar' },
    rahatlar: { e: '😌', t: 'Rahatlar',     id: 'emp-rahatlar' },
    gururlanir:{ e: '😎', t: 'Gurur duyar', id: 'emp-gururlanir' },
    kizar:    { e: '😤', t: 'Kızar',        id: 'emp-kizar' }
  },
  durumlar: [
    { e: '🍪', soru: 'Kurabiyemizi arkadaşımızla paylaştık. O ne hisseder?', dogru: 'sevinir', id: 'empati-1',
      neden: 'Paylaşmak karşımızdakini mutlu eder. Bizi de.' },
    { e: '🚫', soru: 'Arkadaşımızı oyuna almadık. O ne hisseder?', dogru: 'uzulur', id: 'empati-2',
      neden: 'Dışarıda kalmak çok üzücüdür. Herkesi oyuna alalım.' },
    { e: '🤗', soru: 'Ağlayan arkadaşımıza sarıldık. O ne hisseder?', dogru: 'rahatlar', id: 'empati-3',
      neden: 'Bir sarılmak, yüz söz kadar iyi gelir.' },
    { e: '👏', soru: 'Arkadaşımızın resmini beğendik ve alkışladık. O ne hisseder?', dogru: 'gururlanir', id: 'empati-4',
      neden: 'Emeği görülünce insan kendisiyle gurur duyar.' },
    { e: '😱', soru: 'Arkadaşımızı arkadan bağırarak korkuttuk. O ne hisseder?', dogru: 'korkar', id: 'empati-5',
      neden: 'Şaka sandığımız şey karşımızdakini gerçekten korkutabilir.' },
    { e: '🧸', soru: 'Arkadaşımızın oyuncağını izinsiz aldık. O ne hisseder?', dogru: 'kizar', id: 'empati-6',
      neden: 'İzin istemek çok kolay, üstelik kimseyi kırmaz.' },
    { e: '🩹', soru: 'Düşen arkadaşımızı kaldırdık. O ne hisseder?', dogru: 'rahatlar', id: 'empati-7',
      neden: 'Zor anında yanında olan bir el, insanı rahatlatır.' },
    { e: '🎈', soru: 'Arkadaşımıza balon hediye ettik. O ne hisseder?', dogru: 'sevinir', id: 'empati-8',
      neden: 'Küçük bir hediye bile büyük bir sevinç olur.' },
    { e: '😝', soru: 'Arkadaşımızın adıyla dalga geçtik. O ne hisseder?', dogru: 'uzulur', id: 'empati-9',
      neden: 'Şaka gibi görünen sözler karşımızdakini kırabilir.' },
    { e: '🏆', soru: 'Arkadaşımız yarışmayı kazandı ve onu tebrik ettik. O ne hisseder?', dogru: 'gururlanir', id: 'empati-10',
      neden: 'Tebrik etmek, sevinci ikiye katlar.' },
    { e: '🌙', soru: 'Karanlıkta kalan arkadaşımızın elini tuttuk. O ne hisseder?', dogru: 'rahatlar', id: 'empati-11',
      neden: 'Yalnız olmadığını bilmek korkuyu azaltır.' },
    { e: '🖍️', soru: 'Arkadaşımızın çizimini karaladık. O ne hisseder?', dogru: 'kizar', id: 'empati-12',
      neden: 'Emek verilen bir şeyi bozmak insanı çok kızdırır.' }
  ]
});

/* 3) Paylaşma Zamanı */
window.GamePaylasma = Motor.davranis({
  id: 'paylasma', title: 'Paylaşma<br>Zamanı', emoji: '🎈',
  intro: { id: 'sys-oyun-paylasma', text: 'Paylaşmayı birlikte öğrenelim!' },
  durumlar: [
    { e: '🍫', soru: 'Elimizde iki çikolata var, arkadaşımızın hiç yok.',
      dogru: { e: '🤝', t: 'Birini ona veririz' }, yanlis: { e: '🙅', t: 'İkisini de yeriz' },
      neden: 'Paylaşınca çikolatanın tadı azalmaz ama sevinç ikiye katlanır.', id: 'pay-1' },
    { e: '🖍️', soru: 'Boya kalemlerimiz var, arkadaşımız boyamak istiyor.',
      dogru: { e: '🎨', t: 'Kalemleri paylaşırız' }, yanlis: { e: '🔒', t: 'Kutuyu kapatırız' },
      neden: 'Birlikte boyamak tek başına boyamaktan daha eğlencelidir.', id: 'pay-2' },
    { e: '⚽', soru: 'Topumuzla oynuyoruz, arkadaşımız izliyor.',
      dogru: { e: '👋', t: 'Onu da oyuna çağırırız' }, yanlis: { e: '🏃', t: 'Tek başımıza oynarız' },
      neden: 'İki kişiyle top oyunu çok daha keyiflidir.', id: 'pay-3' },
    { e: '🪑', soru: 'Otobüste tek boş yer var, yaşlı bir teyze ayakta.',
      dogru: { e: '🧓', t: 'Yerimizi veririz' }, yanlis: { e: '😐', t: 'Oturmaya devam ederiz' },
      neden: 'Büyüklerimize yer vermek en güzel davranışlardan biridir.', id: 'pay-4' },
    { e: '🧸', soru: 'Misafir çocuk oyuncağımızla oynamak istiyor.',
      dogru: { e: '😊', t: 'Sırayla oynarız' }, yanlis: { e: '😾', t: 'Elinden çekeriz' },
      neden: 'Sıra ile oynamak, ikimizin de oynaması demektir.', id: 'pay-5' },
    { e: '🥪', soru: 'Arkadaşımız beslenmesini evde unutmuş.',
      dogru: { e: '🍞', t: 'Sandviçimizi bölüşürüz' }, yanlis: { e: '🙈', t: 'Görmezden geliriz' },
      neden: 'Aç kalan bir arkadaşa yardım etmek çok değerlidir.', id: 'pay-6' },
    { e: '📚', soru: 'Kitabımızı arkadaşımız da okumak istiyor.',
      dogru: { e: '👀', t: 'Birlikte bakarız' }, yanlis: { e: '🚷', t: 'Vermeyiz' },
      neden: 'Birlikte kitap bakmak, hikayeyi paylaşmaktır.', id: 'pay-7' },
    { e: '🎂', soru: 'Doğum günü pastamız var, arkadaşlarımız etrafta.',
      dogru: { e: '🍰', t: 'Herkese dilim veririz' }, yanlis: { e: '🍽️', t: 'Hepsini kendimize ayırırız' },
      neden: 'Pasta paylaşıldıkça bayram olur.', id: 'pay-8' },
    { e: '☂️', soru: 'Yağmur yağıyor, arkadaşımızın şemsiyesi yok.',
      dogru: { e: '🤗', t: 'Şemsiyemize alırız' }, yanlis: { e: '🏃', t: 'Koşup gideriz' },
      neden: 'Bir şemsiye iki kişiyi rahatlıkla korur.', id: 'pay-9' },
    { e: '🎮', soru: 'Sırayla oynanan bir oyunda sıramız uzadı.',
      dogru: { e: '⏱️', t: 'Sırayı arkadaşımıza veririz' }, yanlis: { e: '🙉', t: 'Oynamaya devam ederiz' },
      neden: 'Sıra beklemek de vermek de arkadaşlığın parçasıdır.', id: 'pay-10' },
    { e: '🐕', soru: 'Sokakta aç bir kedi gördük, elimizde yiyecek var.',
      dogru: { e: '🐈', t: 'Biraz yiyecek bırakırız' }, yanlis: { e: '👟', t: 'Kovalayıp uzaklaştırırız' },
      neden: 'Hayvanlar da bizim gibi acıkır. Onlara iyi davranmak sevaptır.', id: 'pay-11' },
    { e: '✏️', soru: 'Arkadaşımızın kalemi kırıldı, bizde yedek var.',
      dogru: { e: '🎁', t: 'Yedek kalemi veririz' }, yanlis: { e: '🎒', t: 'Çantada saklarız' },
      neden: 'Kullanmadığımız bir şey, başkasının çok işine yarayabilir.', id: 'pay-12' }
  ]
});

/* 4) Güzel Sözler */
window.GameGuzelsoz = Motor.secmece({
  id: 'guzelsoz', title: 'Güzel<br>Sözler', emoji: '💌',
  intro: { id: 'sys-oyun-guzelsoz', text: 'Hangi durumda ne söyleriz, öğrenelim!' },
  havuz: {
    tesekkur: { e: '🙏', t: 'Teşekkür ederim', id: 'gs-tesekkur' },
    lutfen:   { e: '🥺', t: 'Lütfen',          id: 'gs-lutfen' },
    ozur:     { e: '😞', t: 'Özür dilerim',    id: 'gs-ozur' },
    afiyet:   { e: '🍲', t: 'Afiyet olsun',    id: 'gs-afiyet' },
    gecmis:   { e: '🤒', t: 'Geçmiş olsun',    id: 'gs-gecmis' },
    gunaydin: { e: '🌅', t: 'Günaydın',        id: 'gs-gunaydin' },
    iyigeceler:{ e: '🌙', t: 'İyi geceler',    id: 'gs-iyigeceler' }
  },
  durumlar: [
    { e: '🎁', soru: 'Biri bize hediye verdi, ne deriz?',        dogru: 'tesekkur', id: 'gsz-1',
      neden: 'Teşekkür etmek, verilen emeği gördüğümüzü gösterir.' },
    { e: '🙋', soru: 'Birinden bir şey isteyeceğiz, ne deriz?',  dogru: 'lutfen',   id: 'gsz-2',
      neden: '"Lütfen" demek, isteğimizi kibarca söylemektir.' },
    { e: '💔', soru: 'Yanlışlıkla birini kırdık, ne deriz?',      dogru: 'ozur',     id: 'gsz-3',
      neden: 'Özür dilemek cesaret ister ve kalpleri onarır.' },
    { e: '🍽️', soru: 'Biri yemek yiyor, yanından geçiyoruz. Ne deriz?', dogru: 'afiyet', id: 'gsz-4',
      neden: '"Afiyet olsun" demek güzel bir Türk adetidir.' },
    { e: '🤕', soru: 'Arkadaşımız hasta olmuş, ne deriz?',        dogru: 'gecmis',   id: 'gsz-5',
      neden: '"Geçmiş olsun" demek, iyileşmesini istediğimizi anlatır.' },
    { e: '☀️', soru: 'Sabah uyandık, anneyi gördük. Ne deriz?',   dogru: 'gunaydin', id: 'gsz-6',
      neden: 'Güne güzel bir sözle başlamak günü güzelleştirir.' },
    { e: '🛏️', soru: 'Yatmadan önce ailemize ne deriz?',          dogru: 'iyigeceler', id: 'gsz-7',
      neden: 'İyi dilekle uyumak, huzurlu bir uyku getirir.' },
    { e: '🚪', soru: 'Biri bize kapıyı açtı, ne deriz?',          dogru: 'tesekkur', id: 'gsz-8',
      neden: 'Küçük bir yardım bile teşekkürü hak eder.' },
    { e: '🥤', soru: 'Su istiyoruz, ne diyerek isteriz?',         dogru: 'lutfen',   id: 'gsz-9',
      neden: 'Kibar isteyen çocuğa herkes seve seve yardım eder.' },
    { e: '👟', soru: 'Koşarken birine çarptık, ne deriz?',         dogru: 'ozur',     id: 'gsz-10',
      neden: 'İsteyerek yapmasak da özür dilemek gerekir.' },
    { e: '🩹', soru: 'Arkadaşımız düşüp dizini yaralamış, ne deriz?', dogru: 'gecmis', id: 'gsz-11',
      neden: 'Acı çeken birine güzel söz merhem gibidir.' },
    { e: '🍳', soru: 'Annemiz kahvaltı hazırladı, sofraya oturduk. Ne deriz?', dogru: 'tesekkur', id: 'gsz-12',
      neden: 'Bizim için emek verene teşekkür etmeyi unutmayalım.' }
  ]
});

/* 5) Arkadaşlık Görevleri */
window.GameGorev = Motor.davranis({
  id: 'gorev', title: 'Arkadaşlık<br>Görevleri', emoji: '⭐',
  intro: { id: 'sys-oyun-gorev', text: 'İyi bir arkadaş nasıl davranır, bakalım!' },
  durumlar: [
    { e: '😢', soru: 'Arkadaşımız ağlıyor, ne yaparız?',
      dogru: { e: '🤗', t: 'Yanına gider, sorarız' }, yanlis: { e: '😑', t: 'Görmezden geliriz' },
      neden: 'Yanında olmak, en büyük arkadaşlıktır.', id: 'grv-1' },
    { e: '🆕', soru: 'Sınıfa yeni bir arkadaş geldi.',
      dogru: { e: '👋', t: 'Merhaba der, tanışırız' }, yanlis: { e: '🙈', t: 'Uzak dururuz' },
      neden: 'Yeni gelen çocuk yalnız hisseder. Bir "merhaba" her şeyi değiştirir.', id: 'grv-2' },
    { e: '🏗️', soru: 'Arkadaşımızın kulesi yıkıldı.',
      dogru: { e: '🧱', t: 'Birlikte yeniden yaparız' }, yanlis: { e: '😂', t: 'Gülüp geçeriz' },
      neden: 'Zor anında gülmek değil, yardım etmek gerekir.', id: 'grv-3' },
    { e: '🤫', soru: 'Arkadaşımız bize bir sır verdi.',
      dogru: { e: '🔒', t: 'Sırrını saklarız' }, yanlis: { e: '📢', t: 'Herkese anlatırız' },
      neden: 'Sır saklamak, güvenilir bir arkadaş olmaktır.', id: 'grv-4' },
    { e: '🏅', soru: 'Arkadaşımız yarışmada bizi geçti.',
      dogru: { e: '👏', t: 'Onu tebrik ederiz' }, yanlis: { e: '😤', t: 'Küseriz' },
      neden: 'Kazananı tebrik etmek, güçlü bir kalp ister.', id: 'grv-5' },
    { e: '🍬', soru: 'Arkadaşımız bize şeker ikram etti.',
      dogru: { e: '💐', t: '"Allah razı olsun" deriz' }, yanlis: { e: '🤐', t: 'Sessizce alırız' },
      neden: 'İkram edene teşekkür etmek, ikramı güzelleştirir.', id: 'grv-6' },
    { e: '🎒', soru: 'Arkadaşımızın çantası çok ağır.',
      dogru: { e: '💪', t: 'Taşımasına yardım ederiz' }, yanlis: { e: '🚶', t: 'Önden yürürüz' },
      neden: 'Yardım etmek yorucu değil, güzeldir.', id: 'grv-7' },
    { e: '😠', soru: 'Arkadaşımızla kavga ettik.',
      dogru: { e: '🤝', t: 'Barışmak için ilk adımı atarız' }, yanlis: { e: '⛔', t: 'Bir daha konuşmayız' },
      neden: 'İlk adımı atan, en güçlü olandır.', id: 'grv-8' },
    { e: '🎨', soru: 'Arkadaşımız güzel bir resim yaptı.',
      dogru: { e: '✨', t: '"Maşallah, çok güzel" deriz' }, yanlis: { e: '😒', t: '"Benimki daha iyi" deriz' },
      neden: 'Övmek insanı büyütür, kıyaslamak küçültür.', id: 'grv-9' },
    { e: '🍽️', soru: 'Arkadaşımız yemeğini yere döktü.',
      dogru: { e: '🧻', t: 'Temizlemesine yardım ederiz' }, yanlis: { e: '🤣', t: 'Kahkahayla güleriz' },
      neden: 'Herkesin başına gelebilir. Gülmek yerine yardım edelim.', id: 'grv-10' },
    { e: '🧩', soru: 'Arkadaşımız yapbozu çözemiyor.',
      dogru: { e: '💡', t: 'İpucu verir, birlikte deneriz' }, yanlis: { e: '🙌', t: 'Elinden alıp biz yaparız' },
      neden: 'Yardım etmek, onun yerine yapmak değildir.', id: 'grv-11' },
    { e: '🎂', soru: 'Arkadaşımızın doğum günü.',
      dogru: { e: '🎉', t: 'Kutlar, sevindiririz' }, yanlis: { e: '😶', t: 'Hiçbir şey demeyiz' },
      neden: 'Hatırlanmak, insanı çok mutlu eder.', id: 'grv-12' }
  ]
});

/* 6) Dostluk Bahçesi — iyilik yaptıkça bahçe çiçeklenir */
window.GameBahce = Motor.davranis({
  id: 'bahce', title: 'Dostluk<br>Bahçesi', emoji: '🌷',
  intro: { id: 'sys-oyun-bahce', text: 'Her güzel davranış bahçemizde bir çiçek açtırır!' },
  odul: ['🌱', '🌿', '🌸', '🌷', '💐', '🏡'],
  durumlar: [
    { e: '🌱', soru: 'Bahçeye yeni bir fide diktik. Ne yaparız?',
      dogru: { e: '💧', t: 'Her gün suveririz' }, yanlis: { e: '😴', t: 'Unuturuz' },
      neden: 'Sevgi gibi, bitkiler de düzenli bakım ister.', id: 'bhc-1' },
    { e: '🐦', soru: 'Bahçede yavru bir kuş bulduk.',
      dogru: { e: '🪹', t: 'Dokunmadan yuvasına bakarız' }, yanlis: { e: '✋', t: 'Alıp eve götürürüz' },
      neden: 'Yavru kuşun annesi genelde yakındadır. Dokunmamak en iyisidir.', id: 'bhc-2' },
    { e: '🌸', soru: 'Bahçedeki çiçekler çok güzel açmış.',
      dogru: { e: '👀', t: 'Bakar, koklarız' }, yanlis: { e: '✂️', t: 'Hepsini koparırız' },
      neden: 'Koparılan çiçek solar, dalında kalan herkesi sevindirir.', id: 'bhc-3' },
    { e: '🗑️', soru: 'Bahçede yerde çöp gördük.',
      dogru: { e: '♻️', t: 'Alıp çöp kutusuna atarız' }, yanlis: { e: '👟', t: 'Üstünden atlarız' },
      neden: 'Bizim atmadığımız çöpü almak, çevreye iyilik yapmaktır.', id: 'bhc-4' },
    { e: '🐜', soru: 'Yolda karınca sırası var.',
      dogru: { e: '🦶', t: 'Dikkatle etrafından geçeriz' }, yanlis: { e: '💥', t: 'Üzerinden basarız' },
      neden: 'En küçük canlının bile yaşama hakkı vardır.', id: 'bhc-5' },
    { e: '🐈', soru: 'Bahçede susamış bir kedi var.',
      dogru: { e: '🥣', t: 'Bir kap su koyarız' }, yanlis: { e: '🚫', t: 'Kovalarız' },
      neden: 'Bir kap su, bir canı hayatta tutar.', id: 'bhc-6' },
    { e: '🍂', soru: 'Bahçe yapraklarla dolmuş.',
      dogru: { e: '🧹', t: 'Süpürmeye yardım ederiz' }, yanlis: { e: '📺', t: 'İçeri kaçarız' },
      neden: 'Yardım eden eller, bahçeyi bir günde toparlar.', id: 'bhc-7' },
    { e: '🌳', soru: 'Ağacın dalları meyve dolu.',
      dogru: { e: '🍎', t: 'İhtiyacımız kadar alırız' }, yanlis: { e: '🪓', t: 'Dalı kırarız' },
      neden: 'Dalı kırarsak gelecek yıl meyve olmaz.', id: 'bhc-8' },
    { e: '🦋', soru: 'Bahçede kelebek uçuyor.',
      dogru: { e: '😊', t: 'İzler, keyfini çıkarırız' }, yanlis: { e: '🕸️', t: 'Yakalayıp kavanoza koyarız' },
      neden: 'Kelebekler özgür uçtuklarında en güzeldir.', id: 'bhc-9' },
    { e: '💦', soru: 'Bahçeyi sularken hortumu açık unuttuk.',
      dogru: { e: '🚰', t: 'Hemen kapatırız' }, yanlis: { e: '🤷', t: 'Aksın diye bırakırız' },
      neden: 'Su çok değerlidir, boşa akıtmamak gerekir.', id: 'bhc-10' },
    { e: '🧒', soru: 'Küçük komşumuz bahçede oynamak istiyor.',
      dogru: { e: '🤗', t: 'Onu da davet ederiz' }, yanlis: { e: '🚪', t: 'Kapıyı kaparız' },
      neden: 'Paylaşılan bahçe daha neşeli olur.', id: 'bhc-11' },
    { e: '🌻', soru: 'Komşumuzun çiçeği solmuş, o tatilde.',
      dogru: { e: '💧', t: 'Biz sularız' }, yanlis: { e: '😐', t: '"Bana ne" deriz' },
      neden: 'Komşu hakkı, bakılması gereken güzel bir emanettir.', id: 'bhc-12' }
  ]
});
